name:  Build and Test Flutter App
on: [push,pull_request]

jobs:
  test:
    runs-on: macos-latest
    #sequence of tasks called
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter pub get
      # run static analys code
    - run: flutter analyze

  e2e-test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

          #script: | 
           #flutter drive --target=test_driver/app.dart --driver=test_driver/key_new.dart 
           #flutter drive --target=test_driver/app.dart --driver=test_driver/key_imported.dart
